#executable              = /afs/cern.ch/work/v/vyeroshe/Plume_vdm/plume-vdm/decoding/run_thread.sh
#arguments               = $(i_thrd) 
#initialdir              = /afs/cern.ch/work/v/vyeroshe/Plume_vdm/plume-vdm/decoding/
#error                   = /afs/cern.ch/work/v/vyeroshe/Plume_vdm/plume-vdm/decoding/logs/errors.$(i_thrd).txt
#log                     = /afs/cern.ch/work/v/vyeroshe/Plume_vdm/plume-vdm/decoding/logs/log.$(i_thrd).log

executable              = /afs/cern.ch/work/v/vyeroshe/Plume_vdm/plume-vdm/decoding/run_thread.sh
arguments               = $(Process) 
initialdir              = /afs/cern.ch/work/v/vyeroshe/Plume_vdm/plume-vdm/decoding/
error                   = /afs/cern.ch/work/v/vyeroshe/Plume_vdm/plume-vdm/decoding/logs2/errors.$(Process).txt
log                     = /afs/cern.ch/work/v/vyeroshe/Plume_vdm/plume-vdm/decoding/logs2/log.$(Process).log

transfer_input_files	= plume2.py, run_thread.sh

should_transfer_files   = IF_NEEDED
when_to_transfer_output = ON_EXIT

request_memory          = 5 GB
# +JobFlavour = "espresso"
+JobFlavour = "longlunch"
# +JobFlavour = "workday"
getenv = True

# expected_runtime_minutes = 20
# #
# # Should not need to change the below...
# #
# job_machine_attrs = Machine
# job_machine_attrs_history_length = 4
# requirements = target.machine =!= MachineAttrMachine1 && \
#    target.machine =!= MachineAttrMachine2 && \
#    target.machine =!= MachineAttrMachine3
# periodic_hold = JobStatus == 2 && \
#    CurrentTime - EnteredCurrentStatus > 60 * $(expected_runtime_minutes)
# periodic_hold_subcode = 1
# periodic_release = HoldReasonCode == 3 && HoldReasonSubCode == 1 && \
#    JobRunCount < 3
# periodic_hold_reason = ifthenelse(JobRunCount<3,"Ran too long, will retry","Ran too long")

# queue FILE matching (
#     #/eos/lhcb/point8/lhcb/data/2022/RAW/FULL/LHCb/CALIBRATION22/235932/235932_00140007_1069.raw
#     /eos/lhcb/point8/lhcb/data/2022/RAW/FULL/LHCb/CALIBRATION22/235932/*.raw
#  )

queue 166

#queue 1 i_thrd in 19, 71, 78